[package]
name = "build_page"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.60"
thiserror = "1.0.32"
comrak = { path = "../comrak" }
syntect = "4.6.0"
